# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r_build_args: --no-build-vignettes
r_check_args: --no-build-vignettes
warnings_are_errors: false